import type { QueueItem } from "./queue-types"

export const mockQueueItems: QueueItem[] = [
  {
    id: "q1",
    customerId: "c1",
    petId: "p1",
    queueNumber: "N-001",
    customerName: "Olimjon Qodirov",
    petName: "Rex",
    petSpecies: "Inson",
    doctor: "Dr. Alisher",
    status: "in-progress",
    priority: "normal",
    checkinTime: new Date(new Date().getTime() - 15 * 60000),
    calledTime: new Date(new Date().getTime() - 5 * 60000),
    estimatedWaitTime: 0,
    service: "Inspection + Treatment",
  },
  {
    id: "q2",
    customerId: "c2",
    petId: "p3",
    queueNumber: "N-002",
    customerName: "Zaroat Rashidova",
    petName: "Bars",
    petSpecies: "Inson",
    doctor: "Dr. Fatima",
    status: "called",
    priority: "normal",
    checkinTime: new Date(new Date().getTime() - 10 * 60000),
    calledTime: new Date(),
    estimatedWaitTime: 0,
    service: "Vaccination",
  },
  {
    id: "q3",
    customerId: "c3",
    petId: "p4",
    queueNumber: "N-003",
    customerName: "Kamron Mirzoev",
    petName: "Lucky",
    petSpecies: "Inson",
    status: "waiting",
    priority: "normal",
    checkinTime: new Date(new Date().getTime() - 5 * 60000),
    estimatedWaitTime: 10,
    service: "Checkup",
  },
  {
    id: "q4",
    customerId: "c1",
    petId: "p2",
    queueNumber: "N-004",
    customerName: "Olimjon Qodirov",
    petName: "Mimi",
    petSpecies: "Inson",
    status: "waiting",
    priority: "routine",
    checkinTime: new Date(new Date().getTime() - 2 * 60000),
    estimatedWaitTime: 20,
    service: "Dental cleaning",
  },
  {
    id: "q5",
    customerId: "c2",
    petId: "p3",
    queueNumber: "N-005",
    customerName: "Zaroat Rashidova",
    petName: "Bars",
    petSpecies: "Inson",
    status: "waiting",
    priority: "urgent",
    checkinTime: new Date(),
    estimatedWaitTime: 30,
    notes: "Emergency - severe limping",
    service: "Emergency consultation",
  },
]
