import type { Customer, Invoice } from "./types"

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    name: "Olimjon Qodirov",
    phone: "+998901234567",
    email: "olimjon@example.com",
    address: "Tashkent, Shayxontahur",
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2025-01-22"),
    pets: [
      {
        id: "p1",
        customerId: "c1",
        name: "Alijon",
        species: "Inson",
        breed: "Shepherd",
        age: 3,
        weight: 30,
        color: "Qora",
        microchip: "MC123456",
        createdAt: new Date("2024-06-15"),
        updatedAt: new Date("2025-01-22"),
        medicalRecords: [
          {
            id: "mr1",
            petId: "p1",
            date: new Date("2025-01-15"),
            recordType: "diagnoz",
            description: "Og'riq ko'z, qo'zg'olis yallig'lanish",
            vetName: "Dr. Alisher",
            followUpDate: new Date("2025-02-15"),
          },
          {
            id: "mr2",
            petId: "p1",
            date: new Date("2024-12-20"),
            recordType: "dori",
            description: "Antibiotik kursini o'tkazish boshlanishi",
            vetName: "Dr. Fatima",
            followUpDate: new Date("2025-01-10"),
          },
        ],
        visits: [
          {
            id: "v1",
            petId: "p1",
            date: new Date("2025-01-15"),
            vetNotes: "Og'riq ko'z kasalligi aniqland",
            diagnosis: "Qo'zg'olis yallig'lanishi",
            symptoms: ["Qo'qqoq suvush", "Ko'z qizarish"],
            services: [
              { id: "s1", name: "Inspection", price: 100000, category: "inspection" },
              { id: "s2", name: "Dori", price: 150000, category: "treatment" },
            ],
            invoiceId: "inv1",
            followUpDate: new Date("2025-02-15"),
          },
        ],
      },
      {
        id: "p2",
        customerId: "c1",
        name: "Lola",
        species: "Inson",
        breed: "Siamese",
        age: 2,
        weight: 4,
        color: "Oq",
        createdAt: new Date("2024-10-10"),
        updatedAt: new Date("2025-01-22"),
        medicalRecords: [],
        visits: [],
      },
    ],
  },
  {
    id: "c2",
    name: "Zaroat Rashidova",
    phone: "+998902345678",
    email: "zaroat@example.com",
    address: "Tashkent, Yunusabad",
    createdAt: new Date("2024-09-20"),
    updatedAt: new Date("2025-01-20"),
    pets: [
      {
        id: "p3",
        customerId: "c2",
        name: "Bars",
        species: "Inson",
        breed: "Alabay",
        age: 5,
        weight: 45,
        color: "Qara-oq",
        createdAt: new Date("2024-09-20"),
        updatedAt: new Date("2025-01-20"),
        medicalRecords: [],
        visits: [],
      },
    ],
  },
  {
    id: "c3",
    name: "Kamron Mirzoev",
    phone: "+998903456789",
    email: "kamron@example.com",
    address: "Tashkent, Chilanzar",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2025-01-18"),
    pets: [
      {
        id: "p4",
        customerId: "c3",
        name: "Lucky",
        species: "Inson",
        breed: "Poodle",
        age: 1,
        weight: 10,
        color: "Oq",
        createdAt: new Date("2024-08-15"),
        updatedAt: new Date("2025-01-18"),
        medicalRecords: [],
        visits: [],
      },
      {
        id: "p5",
        customerId: "c3",
        name: "Fluffy",
        species: "Inson",
        breed: "Persian",
        age: 3,
        weight: 5,
        color: "Rang",
        createdAt: new Date("2024-06-01"),
        updatedAt: new Date("2025-01-18"),
        medicalRecords: [],
        visits: [],
      },
      {
        id: "p6",
        customerId: "c3",
        name: "Tweety",
        species: "Inson",
        breed: "Parrot",
        age: 2,
        weight: 0.5,
        color: "Rang",
        createdAt: new Date("2024-07-20"),
        updatedAt: new Date("2025-01-18"),
        medicalRecords: [],
        visits: [],
      },
    ],
  },
]

export const mockPaymentMethods = [
  { id: "m1", name: "Naqd pul", type: "cash" },
  { id: "m2", name: "Debit karta", type: "card" },
  { id: "m3", name: "Bank o'tkazmasi", type: "transfer" },
  { id: "m4", name: "Onlayn to'lov", type: "online" },
]

// Enhanced invoices with more data
export const mockInvoices: Invoice[] = [
  {
    id: "inv1",
    visitId: "v1",
    customerId: "c1",
    petName: "Alijon",
    date: new Date("2025-01-15"),
    totalAmount: 250000,
    services: [
      { id: "s1", name: "Tekshirish", price: 100000, category: "inspection" },
      { id: "s2", name: "Dori", price: 150000, category: "treatment" },
    ],
    payments: [
      {
        id: "p1",
        invoiceId: "inv1",
        amount: 150000,
        date: new Date("2025-01-15"),
        method: "cash",
        notes: "Qabul paytida to'landi",
      },
    ],
    status: "partial",
    dueDate: new Date("2025-02-15"),
    notes: "Antibiotik kursidan keyin qayta kelish kerak",
  },
  {
    id: "inv2",
    visitId: "v2",
    customerId: "c2",
    petName: "Bars",
    date: new Date("2024-12-20"),
    totalAmount: 450000,
    services: [
      { id: "s3", name: "Operatsiya", price: 300000, category: "surgery" },
      { id: "s4", name: "Kasallik ko'rikma", price: 150000, category: "inspection" },
    ],
    payments: [],
    status: "unpaid",
    dueDate: new Date("2025-01-20"),
    notes: "Muddati o'tgan qarz",
  },
  {
    id: "inv3",
    visitId: "v3",
    customerId: "c3",
    petName: "Lucky",
    date: new Date("2025-01-10"),
    totalAmount: 180000,
    services: [{ id: "s5", name: "Emlanish", price: 180000, category: "vaccination" }],
    payments: [
      {
        id: "p2",
        invoiceId: "inv3",
        amount: 180000,
        date: new Date("2025-01-10"),
        method: "card",
        notes: "Karta orqali to'landi",
      },
    ],
    status: "paid",
    dueDate: new Date("2025-02-10"),
    notes: "",
  },
]

export const mockDebts = mockInvoices
  .filter((inv) => inv.status !== "paid")
  .map((inv) => ({
    id: inv.id,
    customerId: inv.customerId,
    invoiceId: inv.id,
    customerName: mockCustomers.find((c) => c.id === inv.customerId)?.name || "",
    petName: inv.petName,
    totalAmount: inv.totalAmount,
    paidAmount: inv.payments.reduce((sum, p) => sum + p.amount, 0),
    remainingAmount: inv.totalAmount - inv.payments.reduce((sum, p) => sum + p.amount, 0),
    daysOverdue: Math.max(0, Math.floor((Date.now() - inv.dueDate!.getTime()) / (1000 * 60 * 60 * 24))),
    status: inv.status,
    invoiceDate: inv.date,
    dueDate: inv.dueDate,
  }))
